env:
  - name: PW_SOURCES
    value: /config/sources.yaml

extraVolumes:
  - name: pgwatch-sources
    secret:
      secretName: pgwatch-sources-secret

extraVolumeMounts:
  - name: pgwatch-sources
    mountPath: /config/sources.yaml
    subPath: sources.yaml

pgwatch:
  env:
    - name: PW_SOURCES
      value: /config/sources.yaml
  extraVolumes:
    - name: pgwatch-sources
      secret:
        secretName: pgwatch-sources-secret
  extraVolumeMounts:
    - name: pgwatch-sources
      mountPath: /config/sources.yaml
      subPath: sources.yaml
  postgres:
    enablePgSink: false
    credentials:
      username: "pgwatch"
      password: "dummyPassword123!"
    adminCredentials:
      password: "dummyAdminPassword123!"
  prometheus:
    enablePromSink: true
    newPrometheus:
      createPrometheus: false
  grafana:
    enableGrafana: false
  sources:
    files: {}
