pgwatch:
  service:
    ports:
      - name: pgwatch
        port: 8080
        targetPort: 8080
        protocol: TCP
      - name: prometheus
        port: 9188
        targetPort: 9188
        protocol: TCP
  postgres:
    enablePgSink: false
    credentials:
      username: "pgwatch"
      password: "dummyPassword123!"
    adminCredentials:
      password: "dummyAdminPassword123!"
  prometheus:
    enablePromSink: true
    newPrometheus:
      createPrometheus: false
  grafana:
    enableGrafana: false
  sources:
    files: {} #Leave emplty to avoid creating plain ConfigMaps
