apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pgwatch
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - pgwatch
  selector:
    matchLabels:
      app.kubernetes.io/name: pgwatch
  podMetricsEndpoints:
    - targetPort: 9188
      interval: 15s
      path: /metrics
