---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgwatch-sources-secret
  namespace: pgwatch
spec:
  encryptedData:
    sources.yaml: AgBTVUATDConxmPofRKfmh+MUWJUKkCk9sfq20FDgqLuCbTutWCoqsYgzUKQTeUQDMxe6+HoRpaNZMEDQvSTcMChODFDEEVSHFb0jKXgaRGST2Gf4Blry3uPt/oye2iavjPy6bo96vWjKJWgtEzWPeyrCpkwUJu9jblAbwJMNx5w4iusho8MZvnBX+7MQ9PO0gpztfNkZ81SQNS/Ec3Mfzho40aAsKNQosvhYBtFq1pm9H2mJOGGsRYAe4hGiRpUVuhgFX1fi93S9EFOEyMsXp4EpPQsdV9UrxoNP5L9qQkE6nOQ4XmPWQNad8tBGT7LCSMYL5yqxy1XcTkUm0ePZ3I71sm7/eBcc7nngswgSQnR7GfINUJNtyX8ylhtfrNuBAO+FmkTI+iJr9OPMV2lAeichTW2SrowfgVt+iKPsg3TdOEjFLAWYO7lplT+y7FFR6UIXB483Wev7Eyf4EVnlSopCcU9zoTTBgDE7fryN50JLjBeBaCqaubyvIUZxrgzefa/42agzGO64WXMcmWmkwx/9z+u9YxwIWv9t7gUhFaPI+GO3cdcMAuaVh7rgoAFeH2NhDhlMAzBkNeHY7OthGKCN6kLKdNVbYPyQAyc2GDswiO3NWITl//85J6TM7x4SIKWnmdnPXc+SrAXxcwlVhA0Hd+MJLx8ANF2p73EBhXYdWuDgO2I/dP0NNRzRHac0hpG5eiW1Ot5R0sLX+HiGXKnrCZbK13TnjoEbOu9L/h01JnS6gN1VavPJrKM3ZxHRxKLSCEmRSlZsRpeXsO0zBwKoccXfQaEdx1m/olrVY48MbPPWR4b71B/HzgGCEBtKo4GRzGlsTIbCD6Poz8QzwMKFey1/esJfOsvBWEzJb8iAYvI51q4ett2x7/2OT4fz07Y39WvGl4OEu0WyY/uiJbimYIC4fSnSTnLBMQfankkxP6nOYvjEei9NNRc42zIYsTQtn7dI3fSmsY00NPMhe1bg9s6EhmQ/ZJXqsW6Z3kdioby/vmYqe4TgOyJtFF8uL6ZLIGb+LX7j4qMZ8Zyc7+MSjBCj4tEYosGVykriLa3HMmgJicZr5at3hX7GPOCbQ3aBAabm0REjRM=
  template:
    metadata:
      name: pgwatch-sources-secret
      namespace: pgwatch
