---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgwatch-sources-secret
  namespace: pgwatch
spec:
  encryptedData:
    sources.yaml: AgBrLW+sdjLfInFgHnIJrM55RcYayxX0i3ovJmxqz4yhFpZsGSPDrjFKhvnGsFEF184rZQhjRjThYCAYzbJcjze+rMkwkBHtNjwgPIcNr4GzFDyaMwSKlab6GddN5Bx63YxwN3mqi2KhJ/kkiovTssPsBgd/5mj6hISa/rphAGliuVG0dG/caMZOzeU1FArXqaRc4LvuQdqUYvNqNXKjFEQTUBL6M2i2vevA/vsedIxvyKV8VfHIGa83TuqCaGUEw+MIDFcex4XAeXvrKCV3GnJB0kEvf3fWx/27flI4afwUGvYHvVuycZgT2wnVvu8hM7OoQY+955D7nbXnew1vFScrqKe5XzapfpUN6gW6KVHJAdrvEcGcQdcpBf/kifLQ4+/ngiunsN9K+Db17MlAhhF4tKNhZLGiV3uHT/aVyGaVQrN/5zMZvHCohanIzEK7GsWdXKeModaNttyPET+zA8EQdJxk9+whKq1rV5HYX5gu8utHhbAjy3kxP2c4TFi9k0+ZxaD5DSq3rVV45uTwf5O6CL9vM/kvZk+qRuA0OqqjWVkuIqoMdgYwNAiubYrK+bfUOSvK2fQOD9pjG4P+k0C5Yr3RVX3/2zJ/6Bp/dJ3OFf7mewWnlYxeDDLd6w9zUdTJTABtVcGMfwLXgZiTsvtxVGm7CQM63tMi3+5i0/kWxlOzWmuH5eQKxuGU7J9P4Vnli2Y4aca2F4s0uZSkTUtTxImgz0uSjf37NbP/jOG1c03p36b/8ZEn9wuUUOC/oK9oyyX2QikAUH+PhOVZ7DgHVaBVSpgWLzgHH5qzu1NSjAkewKSAPYU3pUzUhYg1UV27rrXOg4jQW8wedqQQQhrKxIvi3Wy1xQAHhT0Dbewr8sysv5gjuSvU1lhMKX8z+F2r4hWJzrRt4p3iJTIuz9JjmcmshB2t2e+dIyKQLajCFrorDK5IUT+QDQ5qLNXZcDNFPoKEQ37Ooeaa+nW8LXPpeObTwuJQOLCxX+Age09ZanBjA4U9aLv6RvjpjPajM1BrWgkRd0WKV0Xy81+TQ1uhYFpLBb+HiSBVu74O/pf5t/P8OSqWF1zB27XWM+SYq8KhRizxO0bA372wpBaSWiIjxg37
  template:
    metadata:
      name: pgwatch-sources-secret
      namespace: pgwatch
